name: "Publish npm package"

jobs:
  build:
    uses: './.github/workflows/go.yml'

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}